### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jtrent238**
Made a clickable link
[cirections.html](https://pste.eu/p/AHXU.html)

### CODE REVIEW

**Comment by sofar** [comment]
Where does this URL come from? We shouldn't insert redirects to pages that are third-party.

**Comment by sofar** [comment]
Better convert the directions to .md. This is not ok.

**Comment by jtrent238** [comment]
Its a html pastebin.

**Comment by sofar** [comment]
Adding links to a third-party website is not acceptable nonetheless.

**Comment by jtrent238** [comment]
ok

**Pull request closed without merging**
